"""Profiles = which modules are selected + build options. Stored as JSON files."""
from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path

from pydantic import BaseModel, Field

from . import catalog, config, overlay

SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9_-]{0,63}$")


class Profile(BaseModel):
    slug: str
    name: str
    description: str = ""
    sysmon_version: str = config.DEFAULT_SYSMON_VERSION
    unsupported: str = "warn"          # warn | exclude
    preserve_comments: bool = False
    force_grouprelation_or: bool = False
    analyze: bool = True
    modules: list[str] = Field(default_factory=list)
    created: str = ""
    updated: str = ""

    @property
    def selected(self) -> set[str]:
        return set(self.modules)


def _path(slug: str) -> Path:
    if not SLUG_RE.match(slug):
        raise ValueError(f"invalid profile slug: {slug!r}")
    return config.PROFILES_DIR / f"{slug}.json"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def slugify(name: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", name.strip().lower()).strip("-")[:64]
    if not SLUG_RE.match(s):
        raise ValueError("profile name must contain letters or digits")
    return s


def list_profiles() -> list[Profile]:
    config.ensure_dirs()
    out = []
    for p in sorted(config.PROFILES_DIR.glob("*.json")):
        try:
            out.append(Profile.model_validate_json(p.read_text()))
        except Exception:
            continue
    return out


def load(slug: str) -> Profile:
    return Profile.model_validate_json(_path(slug).read_text())


def save(profile: Profile) -> Profile:
    config.ensure_dirs()
    profile.updated = _now()
    profile.created = profile.created or profile.updated
    # keep only modules that still exist, deduplicated & sorted
    profile.modules = sorted({m for m in profile.modules if overlay.exists(m)})
    _path(profile.slug).write_text(profile.model_dump_json(indent=2))
    return profile


def delete(slug: str) -> None:
    p = _path(slug)
    if p.exists():
        p.unlink()


def create(name: str, select_all: bool = True, **opts) -> Profile:
    slug = slugify(name)
    if _path(slug).exists():
        raise FileExistsError(slug)
    prof = Profile(slug=slug, name=name, modules=catalog.all_module_rels() if select_all else [], **opts)
    return save(prof)


def ensure_default() -> Profile:
    """First run: a profile mirroring upstream's default (every module selected)."""
    profiles = list_profiles()
    if profiles:
        return profiles[0]
    return create("default", description="All upstream modules (equivalent to sysmonconfig.xml)")


# ── include-list import / export (same format as upstream 0_custom_configuration) ──
def parse_list(text: str) -> list[str]:
    """Expand a newline-delimited include list to module paths (directories expand)."""
    rels: list[str] = []
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip().replace("\\", "/").strip("/")
        if not line:
            continue
        if line.endswith(".xml"):
            if overlay.exists(line):
                rels.append(line)
        elif overlay.CATEGORY_RE.match(line):
            rels.extend(catalog.module_rels(line))
    return sorted(set(rels))


def to_include_list(profile: Profile) -> str:
    lines = [f"# Generated by {config.APP_TITLE} – profile '{profile.name}'", f"# Sysmon version: {profile.sysmon_version}", ""]
    current = None
    for rel in sorted(profile.modules):
        cat = rel.split("/")[0]
        if cat != current:
            lines.append(f"\n# {cat}")
            current = cat
        lines.append(rel)
    return "\n".join(lines) + "\n"
